

export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const HANDLE_DRAWER = 'HANDLE_DRAWER'
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS'
export const FETCH_ERROR = 'FETCH_ERROR'